stages:
  - build
  - deploy
  
image: docker/compose:latest
services: 
  - name: docker:dind

build:
  stage: build
  tags:
  - maxi
  script:
  - docker-compose build

deploy:
  only:
  - master
  tags:
  - maxi
  stage: deploy
  script:
  - docker-compose down || true
  - docker-compose up -d
