stages:
  - build
  - deploy
  
image: docker/compose:latest
services: 
  - name: docker:dind

build-app:
  stage: build
  tags:
  - tfoms-app
  script:
  - docker-compose build --no-cache

build-ext:
  stage: build
  tags:
  - tfoms-ext
  script:
  - docker-compose build --no-cache

deploy-app:
  only:
  - master
  tags:
  - tfoms-app
  stage: deploy
  environment:
    name: tfoms-app
  script:
  - docker-compose down || true
  - docker-compose up -d

deploy-ext:
  only:
  - master
  tags:
  - tfoms-ext
  stage: deploy
  environment:
    name: tfoms-ext
  script:
  - docker-compose down || true
  - docker-compose up -d
